@startuml

Package Common {

    Package MondaPart {

        class Monda {
            -dsn
            -sqluser
            -sqlpass
            -url
            -zabbix: **Zabbix**

            +__construct()
            +searchHosts(timeWindow:: **TimeWindow**) = **HostGroup**
            +searchItems(timeWindow:: **TimeWindow**) = **ItemList**
            +searchTimeWindows(start: **DateTime**, end: **DateTime**) = **TimeWindowList**
            +createTimeWindows(start: **DateTime**, end: **DateTime**,seconds) = **TimeWindowList**
        }

        class ItemStat {
            -item **Item**
            -timeWindow: **TimeWindow**
            -min
            -max
            -avg
            -delta
            -stddev
            -cv
        }

        class ItemStatList {
                  
        }

        class TimeWindow {
            -startTime: **DateTime**
            -endTime: **DateTime**
            -zabbix: **Zabbix**
            -name
            -description
            -itemList: **ItemList**
            -hostList: **HostList**

            stats()
        }

        class TimeWindowList {
            -startTime: **DateTime**
            -endTime: **DateTime**
            -name
            
            stats()
        }
    }

    package ZabbixPart {
        class Zabbix {
            -zabbixId
            -url
            -dsn
            -sqluser
            -sqlpass
            -apiuser
            -apipass
            -apiurl
            -api: **ZabbixApi**

            +__construct()
            +searchHosts(groupname) = **HostGroup**
            +searchItems(hostGroup: **HostGroup**, key) = **ItemList**
            +getHistory(itemGroup: **ItemList**, from:**DateTime**, to:**DateTime**, stats:bool, data:bool) = **History**
        }

        class ZabbixList {
        }

        class ZabbixAPI {
        }

        class HostGroup {
            -zabbix: **Zabbix**
            -hostList: **HostList**

            get(host **Host**)
        }

        class History {
            -zabbix: **Zabbix**
            -startTime: **DateTime**
            -endTime: **DateTime**
            -items: **ItemList**
            +data[]
        }

    }

    class HostList {
        -name
        
    }

    class Host {
        -zabbix **Zabbix**
        -name
        -itemGroup: **ItemList**
    }

    class Item {
        -zabbix: **Zabbix**
        -itemid
        -host
        -name
        -key
        -historydays
        -updateinterval

        +expand()
    }

    class ItemList {
        
    }

    class List {
        -array[]: data
        +add(object)
        -del(object)
    }
}

Host *--- ItemList
ItemList o-- Item
ItemList o-- History
HostGroup o-- Host
HostGroup <|-- HostList

ZabbixList <|-- List
HostList <|-- List
ItemList <|-- List
ItemStatList <|-- List
TimeWindowList <|-- List

ZabbixList o-- Zabbix
Monda o-- ZabbixList

ItemStatList *-- ItemStat
ItemStat o-- Item

TimeWindowList o-- TimeWindow
TimeWindow *-- ItemStatList
TimeWindow o-- Host
TimeWindow o-- ItemList

Zabbix o-- ZabbixAPI

@enduml